spring.application.name=demo

# Aiven Cloud MySQL Configuration
spring.datasource.url=jdbc:mysql://mysql-c19083-happy-sales-erp.l.aivencloud.com:21531/defaultdb?sslmode=require&useSSL=true&trustServerCertificate=true&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_7SQl3So54umdhll4xa6
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Auto Table Creation
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false